/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <time.h>

	// function to get server time and adding appropriate delay
void
add_prog_1(char *host)
{
	struct timespec begin, end;
	// start time
	timespec_get(&begin, TIME_UTC);
	
	CLIENT *clnt;
	long  *result_1;
	numbers  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		//end time
		timespec_get(&end, TIME_UTC);
		// calculating corrected time
		printf("Time sent by client = %ld, Corrected time %ld secs %ld nanosecs \n",*result_1, *result_1 + (end.tv_sec - begin.tv_sec)/2, (end.tv_nsec - begin.tv_nsec)/2);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	add_prog_1 (host);
	
exit (0);
}
