/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <stdio.h>
#include <time.h>
#include <math.h>

long *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static long final;
	struct timespec result;
	// clock_t CPU_time_1 = clock();

	timespec_get(&result, TIME_UTC);

	final = result.tv_sec;

	printf("Server time = %d secs\n", final);
	// sending the server time to client
	return &final;
}
